name: dyslexia_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-157.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  email_validator: ^2.1.17
  bottom_navy_bar: ^6.0.0
  firebase_storage: ^11.6.6
  image_picker: ^1.0.7
  cloud_firestore: ^4.15.5
  editable_image: ^2.0.0
  photo_manager: ^3.0.0-dev.2
#  photo_manager: ^2.8.2
  sorting: ^0.0.1
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  get: ^4.6.6
  json_annotation: ^4.8.1
  firebase_analytics: ^10.8.7
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0
  audioplayers: ^6.0.0
  just_audio: ^0.9.37
  flutter_tts: ^4.0.2
#  another_audio_recorder: ^1.1.0
#  flutter_sound: ^9.2.13
  flutter_sound_record: ^3.3.2
#  flutter_sound: ^9.4.11
  firebase_app_check: ^0.2.2+5
#  flutter_audio_recorder2:
#  vosk_flutter: ^0.3.47
#  speech_to_text: ^6.6.1
#  file_picker: ^8.0.3
  permission_handler: ^11.3.1 #^10.1.0
#  permission_handler: ^10.1.0
#  google_speech: ^5.2.0+1
#  loading_indicator: ^3.1.1
#  file_picker: ^8.0.3
#  avatar_glow: ^3.0.1
#  record: ^5.0.5
  voice_to_text: ^1.0.3
  speech_to_text_ultra: ^0.0.3
  speech_to_text: ^6.6.1
  highlight_text: ^1.7.0
  clipboard: ^0.1.3
  url_launcher: ^6.2.6
  avatar_glow: ^3.0.1
  whisper_dart: ^0.0.11
  easy_pie_chart: ^1.0.0
  syncfusion_flutter_charts: ^25.2.4
#  vosk_flutter: ^0.3.48
  file_picker: ^8.0.3
  whisper: ^0.0.0
#  vosk_flutter: ^0.3.48
#  text_to_speech: ^0.2.3
#  google_fonts: ^6.2.1
#  flutter_keyboard_visibility: ^6.0.0
  galaxeus_lib_flutter: ^0.0.10
  universal_io: ^2.2.2
  ffmpeg_dart: ^0.0.0
#  vosk_flutter_2: ^1.0.5
  record: ^5.1.0
  substring_highlight:
  cool_alert: ^1.1.0
#  flutter_ffmpeg: ^0.4.0
  ffmpeg_kit_flutter: ^6.0.3
  string_similarity: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/models/
    - assets/models/ggml-tiny2.bin
    - assets/finish_gifs/
    - assets/for_task/
    - assets/sounds/
    - assets/images/
    - assets/images/with_images_back.png
    - assets/images/match_back.png
    - assets/images/2back_light.png
    - assets/images/agreement_back.png
    - assets/sample.json