// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVrY8RizJbNhTNotnfwr6rokTtkWvqJ90',
    appId: '1:526242642075:web:ce0a8f5993e87b462c2e3e',
    messagingSenderId: '526242642075',
    projectId: 'dyslexia-app-a1efe',
    authDomain: 'dyslexia-app-a1efe.firebaseapp.com',
    storageBucket: 'dyslexia-app-a1efe.appspot.com',
    measurementId: 'G-NJS27XX8JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx7JkLqT68PVJbofj6PbJibPH8wMQEZpg',
    appId: '1:526242642075:android:29103b72a5577b5c2c2e3e',
    messagingSenderId: '526242642075',
    projectId: 'dyslexia-app-a1efe',
    storageBucket: 'dyslexia-app-a1efe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRoyfeLHnQnNnb7x36687pN0vARJz60w',
    appId: '1:526242642075:ios:a250dc7e0109d4062c2e3e',
    messagingSenderId: '526242642075',
    projectId: 'dyslexia-app-a1efe',
    storageBucket: 'dyslexia-app-a1efe.appspot.com',
    androidClientId: '526242642075-1abba7e8m4caqt0nol21hrvorclfdvj3.apps.googleusercontent.com',
    iosClientId: '526242642075-5asnoi3069gpv2g3mch6948d0cm9ou2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.dyslexiaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRoyfeLHnQnNnb7x36687pN0vARJz60w',
    appId: '1:526242642075:ios:967bbfc96803f3972c2e3e',
    messagingSenderId: '526242642075',
    projectId: 'dyslexia-app-a1efe',
    storageBucket: 'dyslexia-app-a1efe.appspot.com',
    androidClientId: '526242642075-1abba7e8m4caqt0nol21hrvorclfdvj3.apps.googleusercontent.com',
    iosClientId: '526242642075-3t2varmpcv43bpqk43i3l21e7sa7cq18.apps.googleusercontent.com',
    iosBundleId: 'com.example.dyslexiaProject.RunnerTests',
  );
}
